travis:
  secure:
    BINSTAR_TOKEN: T+kEetdMBesvtyLNt9VBmGxkgWhszcTcyvtJZAqsPBSXsTSkmx96yESelXl4hR6okkbYyfP0gQk4dkN2bgceDjJdr1oRU2WigO5rDVFByWWydqbqbBmVft9UFkheBCKJ6ShdszjLy0S6W4zY0OpxRH+KInfqNzV9AOS3luWPJn1d9RKwS9yl2zX6VKiPDF4nxcBhm8scRm5LqnPCBzW1DtgrknJrhtXOPYP/14Kg3zu5WKjEgveus8JdwTQuZowOFkvlnPvHBBmUurAJc5cb2UG20/T/z3gQ+niF+m15Sfc5ud2TkK7VqVg6kWSbYVeAIG0GsrMqPdNZpFvaA44nFktlKWEwNB9ErTXPVpohIV2L5RQ5dwet2UObRGmaninLd2WA5diYaEUUf08g/fBbQX4eBHNqRKHXicehmpA1+KCZGhs3breviRrvmvVMTp8QTmyUP+22SLj52mSxMJLmUmeWW4RJUSx8+AAkvvXIS+XMQXFrKEjrykZq+241S0KppFDPdGSg3UJJsEWlDCtaqUaM2ThYdZvA2ma+g6VlTfsgVMRn3VUSmuvNpn++KuwR20GV6P8Qba0+YvQOWmRqclhqub7ck4Vs/CxMUQSHH+Wlv2F55Ef74Zdgp26LsQIBspYyIfmPvFYa7LSLwyi7nUMJnLCSAZTmGEZqNePUbU0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
